---
- name: Install nginx on Debian or Ubuntu
  apt:
    name: nginx

- name: Copy template file to server
  template:
      src: nginx.conf.j2
      dest: /etc/nginx/conf.d/default.conf

- name: Restart nginx to load the new configuration
  service:
      name: nginx
      state: restarted
